version: '2.0'

services:
  openc3-mysql:
    container_name: openc3-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "openc3123456^!"
      MYSQL_USER: 'openc3'
      MYSQL_PASS: 'openc3123456^!'
      TZ: 'Asia/Shanghai'
    image: "mysql:5.7"
    restart: always
    volumes:
      - "/data/open-c3-data/mysql-data:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    networks:
      JobNet:
        aliases:
          - OPENC3_DB_IP

  openc3-server:
    build:
      context: JOB/
    hostname: openc3-srv-docker
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      OPEN_C3_EXIP: ${OPEN_C3_EXIP}
      OPEN_C3_NAME: ${OPEN_C3_NAME}
      OPEN_C3_RANDOM: ${OPEN_C3_RANDOM}
    extra_hosts:
      - "api.agent.open-c3.org:127.0.0.1"
      - "api.job.open-c3.org:127.0.0.1"
      - "api.jobx.open-c3.org:127.0.0.1"
      - "api.ci.open-c3.org:127.0.0.1"
      - "api.connector.open-c3.org:127.0.0.1"
    ports:
      - "80:88"
    volumes:
      - "../../Connector:/data/Software/mydan/Connector"
      - "../../MYDan:/data/Software/mydan/MYDan"
      - "../../JOBX:/data/Software/mydan/JOBX"
      - "../../JOB:/data/Software/mydan/JOB"
      - "../../AGENT:/data/Software/mydan/AGENT"
      - "../../CI:/data/Software/mydan/CI"
      - "../../c3-front:/data/Software/mydan/c3-front"
      - "../../web-shell:/data/Software/mydan/web-shell"
      #- "./JOB/auth:/data/Software/mydan/etc/agent/auth"  
      #- "./JOB/logs:/data/logs" 
      #- "./JOB/glusterfs:/data/glusterfs" 
      - "/data/open-c3-data/auth:/data/Software/mydan/etc/agent/auth"  
      - "/data/open-c3-data/logs:/data/logs" 
      - "/data/open-c3-data/glusterfs:/data/glusterfs" 
      - "/bin/docker:/bin/docker" 
      - "/var/run/docker.sock:/var/run/docker.sock" 
    depends_on:
      - openc3-mysql
    networks:
      JobNet:
        aliases:
          - OPENC3_SERVER_IP

networks:
  JobNet:
    driver: bridge
