---
name: '业务审批人'
option:
  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  approver: "ipowner(${x.instance_ids})"
  title:    "BPM/${_bpmuuid_}/资源回收/AWS/EC2"
  content:  "\n申请人:${_user_}\nBPM单号:${_bpmuuid_}\n申请理由:${x.note}"
