  openc3-cloudmon-${cloudmonid}:
    container_name: openc3-cloudmon-${cloudmonid}
    environment:
      TZ: 'Asia/Shanghai'
      AWS_ACCESS_KEY_ID:     '${c3var.ak}'
      AWS_SECRET_ACCESS_KEY: '${c3var.sk}'
    image: "quay.io/prometheus/cloudwatch-exporter"
    working_dir: /
    restart: always
    volumes:
      - "/data/open-c3-data/cloudmon/task/${taskid}/config.dat:/config/config.yml"
    networks:
      - alise_net
