download:
  - url: "cmd:c3mc-cloud-qcloud-ckafka ak sk ap-beijing | c3mc-base-json2tab InstanceId 实例ID"
    datatype: tsv
    type: storage
    subtype: qcloud-ckafka
    init: ["c3mc-cloud-qcloud.sh"]
    treeinfo:
      treename: "服务树"
      treeinfo:
        - ["实例ID", "instance"]
    util:
      defaulttree: defaulttree.pool
    colmap:
      treename: "服务树"
      uuid: "实例ID" #没有这个可能导致单个资源详情打开无数据
    filter:
      - name: "Vip"
        alias: vip
    outline:
      uuid:
        - "实例ID"
      baseinfo:
        - "Vip"
      system:
        - "ConnectionDomain"
      contact:
        - "服务树"
