download:
  - url: "cmd:c3mc-cloud-qcloud-mongodb ak sk ap-beijing | c3mc-base-json2tab InstanceId 实例ID InstanceName 名称 Region 区域 Zone 所在可用区 InstanceStatusDesc 状态 MongoVersion 引擎版本 MachineType 实例类型 "
    datatype: tsv
    type: database
    subtype: qcloud-mongodb
    init: ["c3mc-cloud-qcloud.sh"]
    treeinfo:
      treename: "服务树"
      treeinfo:
        - ["实例ID", "instance"]
    util:
      defaulttree: defaulttree.pool
    colmap:
      treename: "服务树"
      uuid: "实例ID" #没有这个可能导致单个资源详情打开无数据
    filter:
      - name: "区域"
        alias: 区域
      - name: "所在可用区"
        alias: 所在可用区
      - name: "状态"
        alias: 状态
      - name: "引擎版本"
        alias: 引擎版本
      - name: "实例类型"
        alias: 实例类型
    outline:
      uuid:
        - "实例ID"
      baseinfo:
        - "实例ID"
        - "区域"
        - "所在可用区"
      system:
        - "ConnectionDomain"
      contact:
        - "服务树"
