download:
  - url: 'cmd:c3mc-cloud-huawei-redis ak sk project_id(可以传None) cn-north-4 | c3mc-base-json2tab instance_id 实例ID availability_zone ZoneId'
    datatype: tsv
    type: database
    subtype: huawei-redis
    init: ['c3mc-cloud-huawei.sh']
    treeinfo:
      treename: '服务树'
      treeinfo:
        - [ '实例ID', 'instance' ]
    check:
      col: [ '实例ID' ]
      min: 1
    util:
      defaulttree: defaulttree.pool
    colmap:
      treename: '服务树'
      uuid: '实例ID' #没有这个可能导致单个资源详情打开无数据
    filter:
      - name: 'ZoneId'
        alias: 区域
    outline:
      uuid:
        - '实例ID'
      baseinfo:
        - 'ZoneId'
      system:
        - 'ConnectionDomain'
      contact:
        - '服务树'
