download:
  - 
    url: 'cmd:c3mc-cloud-aliyun-redis ak sk cn-beijing | c3mc-base-json2tab InstanceId 实例ID'
    datatype: tsv
    type:    database
    subtype: aliyun-redis
    treeinfo:
      treename: '服务树'
      treeinfo:
        - [ '实例ID', 'instance' ]
    check:
      col: [ '实例ID' ]
      min: 1
    util:
      defaulttree: defaulttree.pool
    colmap:
      treename: '服务树'
      uuid:     '实例ID' #没有这个可能导致单个资源详情打开无数据
    filter:
      -
        name: 'ZoneId'
        alias: 区域
    outline:
      uuid:
       - '实例ID'
      baseinfo:
       - 'ZoneId'
      system:
       - 'ConnectionDomain'
      contact:
       - '服务树'
