download:
  - url: "cmd:c3mc-cloud-ksyun-krds ak sk cn-beijing-6 | c3mc-base-json2tab DBInstanceIdentifier 实例ID Region 区域 DBInstanceType 实例类型 DBInstanceStatus 状态 EngineVersion 引擎版本  "
    datatype: tsv
    type: database
    subtype: ksyun-krds
    init: ["c3mc-cloud-ksyun.sh"]
    treeinfo:
      treename: "服务树"
      treeinfo:
        - ["实例ID", "instance"]
    util:
      defaulttree: defaulttree.pool
    colmap:
      treename: "服务树"
      uuid: "实例ID" #没有这个可能导致单个资源详情打开无数据
    filter:
      - name: "区域"
        alias: 区域
      - name: "实例类型"
        alias: 实例类型
      - name: "状态"
        alias: 状态
      - name: "引擎版本"
        alias: 引擎版本
    outline:
      uuid:
        - "实例ID"
      baseinfo:
        - "实例ID"
        - "区域"
        - "状态"
      system:
        - "ConnectionDomain"
      contact:
        - "服务树"
