download:
  - url: 'cmd:c3mc-cloud-huawei-ecs ak sk project_id(可以传None) cn-north-4  | c3mc-base-json2tab  id 实例ID name 名称 region_id Region名称 private_ip  内网IP  public_ip 公网IP flavor.id 实例类型 flavor.ram 内存 OS-EXT-SRV-ATTR:hostname 主机名  OS-EXT-AZ:availability_zone 所在可用区 status 状态 metadata.os_type 操作系统 '
    datatype: tsv          # 固定值。表示url中命令最终输出的文件格式
    type:    compute       # 资源类型。cmdb页面中的分类
    subtype: huawei-ecs    # 上面资源类型的子类型。
    mod: [ 'c3mc-cloud-huawei.sh' ]
    treeinfo:
      treename: '服务树'     # 指明哪一列对应服务树。这一列没有对应列，页面显示的值为空
      treeinfo:
        - [ '实例ID', 'instance' ]       # 和监控相关 。 指标是 treeinfo
    check:
      col: [ '实例ID', '名称', '内网IP','公网IP', 'Region名称', '所在可用区', '实例类型', '状态', '操作系统' ] # 打印出的数据必须有的字段
      min: 1                   # url中明林执行后最少一行输出，否则认为出错
    ingestion-node:            # 控制资源在发布时的可见行，但是cmdb里一直可以看见
      name: '名称'
      inip: '内网IP'
      exip: '公网IP'
      tree: '服务树'
      type: huawei-ecs
    util:
      defaulttree: defaulttree.pool       # 默认的服务树，资源归还后被放到这里
    colmap:
      treename: '服务树'
      uuid:     '实例ID'                   # 指明哪一列作为uuid列
    filter:
      -
        name: 'Region名称'
        alias: 区域
      -
        name: '所在可用区'
        alias: 可用区
      -
        name: '实例类型'
        alias: 实例类型
      -
        name: '状态'
        alias: 状态
      -
        name: '操作系统'
        alias: 操作系统
 
    outline:
      uuid:
       - '实例ID'
      baseinfo:
       - 'Region名称'
       - '所在可用区'
      system:
       - '名称'
       - '内网IP'
       - '公网IP'
      contact:
       - '服务树'
