---
name: 申请新增FTP平台账号
option:
  - name: account
    describe: 账户
    type: input
    value: ""

  - name: domain_or_ip
    describe: 域名或IP
    type: input
    value: ""

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/申请新增FTP平台账号"
  content:  |
    账户: ${account}
    域名或IP: ${domain_or_ip}
    申请理由: ${note}
