---
name: 申请业务emr账户
option:
  - name: cluster_name
    describe: 集群名称
    type: input
    value: ""

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/申请业务emr账户"
  content:  |
    集群名称: ${cluster_name}
    申请理由: ${note}
