---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/权限申请/ACL操作(含公有云安全组)"
  content:  |
    BPM标题: 权限申请/ACL操作(含公有云安全组)
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
