---
name: '提交人的领导审批'
option:
#  - describe: 业务审批人
#    name: oaapprover
#    type: input
#    value: ""

  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  approver: "boss(${_user_}) or leader(${_user_})"
  title:    "BPM/${_bpmuuid_}/权限申请/ACL操作(含公有云安全组)"
  content:  |
    BPM标题: 权限申请/ACL操作(含公有云安全组)
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
  relaxed: 1
  submitter: '${_user_}'
