---
option:
  - describe: 域名
    name: domain_name
    type: text
    value: ""
  - describe: 是否被注册
    name: registered
    type: select
    option:
      - Yes
      - No
    value: ""
 
  - describe: 域名所属业务使用范围
    name: scope
    type: select
    option:
      - '海外'
      - '国内'
      - '海外&国内'
    value: ""
 
  - describe: 备案主体
    name: website_belonger
    type: input
    value: ""
    required: true
  - describe: 所属业务
    name: belong
    type: input
    value: ""
 
  - describe: 申请理由
    name: apply_note
    type: text
    value: ""

template_argv:
  title:                "注册域名"
  content:              "注册域名: ${domain_name}\n是否被注册: ${registered}\n域名所属业务使用范: ${scope}\n备案主体:${website_belonger}\n所属业务:${belong}\n申请理由:\n${apply_note}"
