---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/资源申请/谷歌云/修改VM机器类"
  content:  |
    BPM标题: 资源申请/谷歌云/修改VM机器类
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
