---
option:
  - describe: 域名
    name: domain_name
    type: text
    value: ""
  - describe: 原解析
    name: resolve_target
    type: text
    value: ""
 
  - describe: 申请理由
    name: apply_note
    type: text
    value: ""

template_argv:
  title:                "域名删除"
  content:              "域名: ${domain_name}\n原解析: ${resolve_target}\n申请理由:\n${apply_note}"
