---
- labels:
    __metrics_path__: /query_10.60.244.12_query
    instance: 10.60.244.12
    tree_foo: 1
  targets:
  - 10.60.77.73:65112
- labels:
    __metrics_path__: /query_10.60.110.208_query
    instance: 10.60.110.208
    tree_bar: 1
  targets:
  - 10.60.77.73:65112
