# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'openc3-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - OPENC3_ALERTMANAGER_IP:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - openc3_rule.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'openc3'
    file_sd_configs:
      - files:
        - openc3_node_sd.yml

  - job_name: 'cloudmon'
    scrape_interval: 60s
    scrape_timeout: 60s
    file_sd_configs:
      - files:
        - openc3_cloudmon_sd.yml

  - job_name: 'openc3-mysql'
    file_sd_configs:
      - files:
        - openc3_mysql_sd.yml

  - job_name: 'openc3-redis'
    file_sd_configs:
      - files:
        - openc3_redis_sd.yml

  - job_name: 'openc3-treeinfo'
    scrape_interval: 60s
    scrape_timeout: 60s
    metrics_path: /treeinfo.txt
    honor_labels: true
    static_configs:
    - targets: ['OPENC3_SERVER_IP:88']
