---
name: 回收数据库资源
option:
  - name: instance_id
    describe: 数据库实例ID
    type: text
    value: ""
    information: "实例ID 是数据库资源在openc3系统中的实例ID字段的值。多个用英文逗号分隔"

  - name: recycle_date
    describe: 回收日期
    type: input
    value: ""

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/回收数据库资源"
  content:  |
    数据库实例ID: ${instance_id}
    回收日期: ${recycle_date}
    申请理由: ${note}
