---
name: 申请个人aws控制台权限
option:
  - name: email
    describe: 邮箱
    type: input
    value: ""

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/申请个人aws控制台权限"
  content:  |
    邮箱: ${email}
    申请理由: ${note}
