---
name: 重置堡垒机二次认证
option:
  - name: account
    describe: 账号
    type: input
    value: ""

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/重置堡垒机二次认证"
  content:  |
    账号: ${account}
    申请理由: ${note}
