---
- alias: 账号
  name: account
- alias: 资源类型
  name: type
- alias: 资源子类
  name: subtype
- alias: 产品线
  name: 产品线
- alias: 一级部门
  name: 一级部门
- alias: 二级部门
  name: 二级部门
- alias: 业务负责人
  name: 业务负责人
- alias: 运维负责人
  name: 运维负责人
- alias: 部门
  name: 部门
- alias: 服务树游离
  name: luxation
- alias: 审计
  name: audit
