---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/域名解析/删除"
  content:  "\n申请人:${_user_}\n域名:${x.domain}\nBPM单号:${_bpmuuid_}\nURL:${_caseurl_}\n申请理由:${x.note}"
  record: 1
  relaxed: 1
  submitter: '${_user_}'
