---
name: 工单处理
option:
  - describe: 域名
    name: domain
    type: text
    value: ""
  - describe: 原解析
    name: target
    type: text
    value: ""
  - describe: 申请理由
    name: note
    type: text
    value: ""

template_argv:
  title:    "BPM/域名删除"
  content:  "域名: ${domain}\n原解析: ${target}\n申请理由: ${note}"
