---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

  - describe: 申请理由
    name: note
    type: text
    value: 

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/申请服务器权限"
  content:  "\n申请人:${_user_}\n登录账号:${x.account}\n服务器ip列表:${x.ip_list}\nBPM单号:${_bpmuuid_}\n申请理由:${x.note}"
