---
name: 领导审批或者资源owner审批
option:
#  - describe: 运维审批人
#    name: opapprover
#    type: selectx
#    value: ""
#    command: "c3mc-bpm-optionx-opapprover"

  - describe: 申请理由
    name: note
    type: text
    value: 

template_argv:
  approver: "sudoer(${x.auth_type},${_user_}) or ipowner(${x.ip_list})"
  title:    "BPM/${_bpmuuid_}/申请服务器权限"
  content:  "\n申请人:${_user_}\n权限类型:${x.auth_type__alias}\n服务器ip列表:${x.ip_list}\nBPM单号:${_bpmuuid_}\nURL:${_caseurl_}\n申请理由:${x.note}"
  everyone: 1
  relaxed:  1
  record: 1
