---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: selectx
    value: ""
    command: "c3mc-bpm-optionx-opapprover"

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/资源修改/腾讯云/修改CVM机器类型"
  content:  |
    BPM标题: 资源修改/腾讯云/修改CVM机器类型
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
