---
name: 运维审批
option: []

template_argv:
  approver: "${x.dealer}"
  title:    "BPM/${_bpmuuid_}/资源修改/腾讯云/修改CVM机器类型"
  content:  |
    BPM标题: 资源修改/腾讯云/修改CVM机器类型
    BPM地址: ${_caseurl_}

    申请人:${_user_}
    申请理由:${x.note}
  record: 1
  submitter: '${_user_}'
