---
name: SQL操作
option:
  - name: database_addr
    describe: 数据库地址
    type: input
    value: ""
  - name: database_name
    describe: 数据库名称
    type: input
    value: ""
  - name: database_owner
    describe: 数据库所属人
    type: input
    value: ""
  - name: sql
    describe: SQL语句
    type: text
    value: ""
  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  title:    "BPM/SQL操作"
  content:  "数据库地址: ${database_addr}\n数据库名称: ${database_name}\n数据库所属人: ${database_owner}\nSQL语句:${sql}\n申请理由: ${note}"
