---
name: SQL操作
option:
  - name: database_addr
    describe: 数据库地址
    type: input
    value: ""
  - name: database_name
    describe: 数据库名称
    type: input
    value: ""
  - name: database_owner
    describe: 数据库所属人
    type: input
    value: ""

  - name: sql_input_type
    describe: sql输入方式
    option: ["手动填写", "上传附件"]
    type: select
    value: "上传附件"

  - name: sql_code
    describe: SQL语句
    type: text
    value: ""
    show:
      - sql_input_type: [ "手动填写" ]

  - name: sql_file
    describe: SQL附件
    type: file
    value: ""
    show:
      - sql_input_type: [ "上传附件" ]

  - name: note
    describe: 申请理由
    type: text
    value: ""

template_argv:
  notify: '@bpm_notify_dba'
  title:    "BPM/${_bpmuuid_}/SQL操作"
  sql_input_type: ${sql_input_type}
  sql_file: ${sql_file}
  apply_user: '${_user_}'
  content:  |
    BPM标题: SQL操作
    BPM地址: ${_caseurl_}

    数据库地址: ${database_addr}
    数据库名称: ${database_name}
    数据库所属人: ${database_owner}
    SQL语句: base64__${sql_code__base64}__base64
    申请理由: ${note}
