---
option:
  - describe: 域名
    name: domain_name
    type: text
    value: ""
  - describe: 原解析
    name: old_resolve_target
    type: text
    value: ""
  - describe: 解析目的(IP/线路/域名)
    name: resolve_target
    type: text
    value: ""

  - describe: 申请理由
    name: apply_note
    type: text
    value: ""

template_argv:
  ApplyType:             ${apply_type}
  DomainName:            ${domain_name}
  ResolveTarget:         ${resolve_target}
  BusinessNode:          ${business_node}
  OldResolveTarget:      ${old_resolve_target}
  IfDomainHasRegistered: ${if_domain_has_registered}
  WebsiteBelonger:       ${website_belonger}
  Title:                 "域名申请与解析"
  ApplyNote:             ${apply_note}
  IfExt:                 0
#  IfExt: ${if_ext}

