---
option:
  - describe: 域名
    name: domain_name
    type: text
    value: ""
  - describe: 原解析
    name: old_resolve_target
    type: text
    value: ""
  - describe: 解析目的(IP/线路/域名)
    name: resolve_target
    type: text
    value: ""

  - describe: 申请理由
    name: apply_note
    type: text
    value: ""

template_argv:
  title:                "域名解析修改"
  content:              "域名: ${domain_name}\n原解析: ${old_resolve_target}\n解析目的(IP/线路/域名): ${resolve_target}\n申请理由:\n${apply_note}"
