---
option:
  - describe: 域名
    name: domain_name
    type: text
    value: ""
  - describe: 解析目的(IP/线路/域名)
    name: resolve_target
    type: text
    value: ""

  - describe: 是否经营网站(必选)
    name: IsBusiness
    type: select
    option:
      - Yes
      - No
    value: ""
 
  - describe: 所属业务
    name: belong
    type: input
    value: ""
 
  - describe: 申请理由
    name: apply_note
    type: text
    value: ""

template_argv:
  title:    "域名解析新申请"
  content:  "域名: ${domain_name}\n解析目的(IP/线路/域名):\n${resolve_target}\n是否经营网站(必选):\n${IsBusiness}\n所属业务:${belong}\n申请理由:\n${apply_note}"
